### ISSUE TITLE
方便分享下数据集吗

### ISSUE THREAD

**Issue by ggzz158** [zhangzhang66/CHIP2020_Relation#1]
请联系我：844970924@qq.com

**Comment by ggzz158** [comment]
万分感谢

**Comment by zhangzhang66** [comment]
> 请联系我：[844970924@qq.com](mailto:844970924@qq.com)

不好意思，由于这是比赛数据，可以浏览https://biendata.com/官网下载，不太方便分享，望谅解

**Comment by zhangzhiyi0108** [comment]
> 请联系我：[844970924@qq.com](mailto:844970924@qq.com)
不好意思，由于这是比赛数据，可以浏览https://biendata.com/ 官网下载，不太方便分享，望谅解
