### ISSUE TITLE
您好，可以分享一下bert_vectors_768.txt吗？

### ISSUE THREAD

**Issue by xhw205** [zhangzhang66/CHIP2020_Relation#2]
I will get an error
FileNotFoundError: [Errno 2] No such file or directory: '/home/zutnlp/data/bertvec/bert_vectors_768.txt'

**Comment by zhangzhang66** [comment]
不好意思。回复晚了，我把词向量放在这里了，你可以直接。
下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by zhangzhiyi0108** [comment]
> I will get an error
> FileNotFoundError: [Errno 2] No such file or directory: '/home/zutnlp/data/bertvec/bert_vectors_768.txt'

不好意思。回复晚了，我把词向量放在这里了，你可以直接。
下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦
