### ISSUE TITLE
您好，方便分享您的词向量文件吗？

### ISSUE THREAD

**Issue by yeyeyeyeeeee** [zhangzhang66/CHIP2020_Relation#3]

**Comment by zhangzhang66** [comment]
不好意思。回复晚了，我把词向量放在这里了，你可以直接。
下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by zhangzhiyi0108** [comment]
> _No description provided._

不好意思。回复晚了，我把词向量放在这里了，你可以直接。
下载链接: https://pan.baidu.com/s/1B3636iktQo3DGt3ohLorGg 提取码: vhwi 复制这段内容后打开百度网盘手机App，操作更方便哦
